Sử dụng Go module và update godbus lên bản mới nhất
BambooEngine/ibus-bamboo pull request #457
Opened 2023-12-17 14:54 UTC by goatastronaut0212

Sử dụng Go module sẽ dễ quản lý thư viện hơn so với GOPATH nhưng bất lợi của Go module là chúng ta sẽ không dùng được lệnh `make install` trong Makefile bao gồm cả bước `make build` (vì Go module cũng dùng Git để quản lý và vì vài lý do nào đó mà `doas` hay là bản thân user `root` sẽ không thể chạy lệnh tốt được, 1 bài post liên quan đến nó như là [Fix that damn Git Unsafe Repository](https://weblog.west-wind.com/posts/2023/Jan/05/Fix-that-damn-Git-Unsafe-Repository)). Vì vậy mình nghĩ nên tách ra thành 2 bước là `make build` còn `make install` thì cài đặt chỉ cần dùng `sudo`, `doas` hay người dùng `root` là ổn.

Mình nghĩ chưa nên merge vào vì đây chỉ nên là 1 bản draft để tham khảo và vẫn còn bug liên quan đến mấy trình terminal có gì mình sửa sau. Không biết bạn nghĩ sao về việc sử dụng Go module?

PR này cũng liên quan đến PR của [goibus](https://github.com/BambooEngine/goibus) và khi nào PR này đủ tốt thì chúng ta có thể sẽ merge cả 2 cái và mình sẽ sửa lại import thư viện

2024-01-03 02:36 UTC, luongthanhlam commented
Ubuntu 16.04 và 18.04 vẫn chưa hỗ trợ building bằng Go module nên mình chưa muốn sử dụng Go module ở thời điểm hiện tại (ít nhất cho đến khi Ubuntu 24.04 LTS được release)

2024-01-12 09:18 UTC, goatastronaut0212 commented
Mình test lại repo bên mình thì có vẻ như PR này mọi thứ vẫn hoạt động tốt không có vấn đề gì cả như mình từng đề cập. Có lẽ mọi thứ còn lại chỉ là thời gian thôi. Hãy ping mình nếu bạn có ý kiến nào thêm nữa như là việc sửa lại đường dẫn import để có gì mình sửa lại.

2024-05-08 15:37 UTC, luongthanhlam reviewed
Overall LGTM, just have some comments

2024-05-08 15:37 UTC, luongthanhlam commented on src/emoji_test.go
bạn có thể chuyển các file này vào thư mục gốc được không? với go module thì thư mục `src` không cần tồn tại nữa

2024-05-09 15:04 UTC, luongthanhlam requested changes

2024-05-09 15:04 UTC, luongthanhlam commented on Makefile
> +build-vendor:
`build-vendor` có vẻ không cần thiết vì go sẽ tự set `mod=vendor` khi code chứa thư mục `vendor`

2024-05-09 15:04 UTC, luongthanhlam commented on Makefile
> +	CGO_ENABLED=1 go test
```suggestion
	CGO_ENABLED=1 go test ./...
```

2024-05-09 15:04 UTC, luongthanhlam commented on engine.go
> -	"github.com/BambooEngine/goibus/ibus"
bạn có thể revert đoạn này không?

2024-05-09 15:04 UTC, luongthanhlam commented on engine_emoji.go
> -	"github.com/BambooEngine/goibus/ibus"
same here

2024-05-09 15:04 UTC, luongthanhlam commented on go.mod
> -	github.com/BambooEngine/goibus v0.0.0-20200430030917-ea4df577c5d6
same here

2024-05-09 15:08 UTC, luongthanhlam commented on src/github.com/BambooEngine/bamboo-core/rules_parser_test.go
mấy file test này chưa được chuyển sang `vendor`

2024-05-10 03:26 UTC, goatastronaut0212 commented
Xin lỗi mình làm hơi trễ, bạn review lại xem code mình có ổn không.

2024-05-10 03:35 UTC, luongthanhlam commented on Makefile
> +	CGO_ENABLED=1 go test ./vendor/github.com/BambooEngine/bamboo-core/...
nit: dòng này không cần thiết vì lệnh trên đã bao gồm test trong toàn bộ thư mục con rồi

2024-05-10 03:36 UTC, luongthanhlam commented
@goatastronaut0212 LGTM, thank you so much!

2024-05-10 03:36 UTC, merged